/**
 * This work is licensed under the 
 * Creative Commons Attribution-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit 
 * http://creativecommons.org/licenses/by-sa/4.0/ 
 * or send a letter to 
 * Creative Commons, 
 * PO Box 1866, Mountain View, 
 * CA 94042, USA.
 */
/**
 * generated by Xtext 2.13.0
 */
package co.watly;

import co.watly.AbstractVaporRuntimeModule;
import co.watly.converter.VaporValueConverter;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class VaporRuntimeModule extends AbstractVaporRuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return VaporValueConverter.class;
  }
}
