/**
 * This work is licensed under the 
 * Creative Commons Attribution-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit 
 * http://creativecommons.org/licenses/by-sa/4.0/ 
 * or send a letter to 
 * Creative Commons, 
 * PO Box 1866, Mountain View, 
 * CA 94042, USA.
 */
/**
 * generated by Xtext 2.13.0
 */
package co.watly.vapor;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command Rotate</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.watly.vapor.CommandRotate#getDegrees <em>Degrees</em>}</li>
 * </ul>
 *
 * @see co.watly.vapor.VaporPackage#getCommandRotate()
 * @model
 * @generated
 */
public interface CommandRotate extends Command
{
  /**
   * Returns the value of the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Degrees</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Degrees</em>' attribute.
   * @see #setDegrees(double)
   * @see co.watly.vapor.VaporPackage#getCommandRotate_Degrees()
   * @model
   * @generated
   */
  double getDegrees();

  /**
   * Sets the value of the '{@link co.watly.vapor.CommandRotate#getDegrees <em>Degrees</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Degrees</em>' attribute.
   * @see #getDegrees()
   * @generated
   */
  void setDegrees(double value);

} // CommandRotate
