/**
 * This work is licensed under the 
 * Creative Commons Attribution-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit 
 * http://creativecommons.org/licenses/by-sa/4.0/ 
 * or send a letter to 
 * Creative Commons, 
 * PO Box 1866, Mountain View, 
 * CA 94042, USA.
 */
/**
 * generated by Xtext 2.13.0
 */
package co.watly.vapor;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command Left</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see co.watly.vapor.VaporPackage#getCommandLeft()
 * @model
 * @generated
 */
public interface CommandLeft extends CommandCommon
{
} // CommandLeft
