/**
 * This work is licensed under the 
 * Creative Commons Attribution-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit 
 * http://creativecommons.org/licenses/by-sa/4.0/ 
 * or send a letter to 
 * Creative Commons, 
 * PO Box 1866, Mountain View, 
 * CA 94042, USA.
 */
/**
 * generated by Xtext 2.13.0
 */
package co.watly.vapor;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Command Common</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link co.watly.vapor.CommandCommon#getMillisecs <em>Millisecs</em>}</li>
 * </ul>
 *
 * @see co.watly.vapor.VaporPackage#getCommandCommon()
 * @model
 * @generated
 */
public interface CommandCommon extends Command
{
  /**
   * Returns the value of the '<em><b>Millisecs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Millisecs</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Millisecs</em>' attribute.
   * @see #setMillisecs(int)
   * @see co.watly.vapor.VaporPackage#getCommandCommon_Millisecs()
   * @model
   * @generated
   */
  int getMillisecs();

  /**
   * Sets the value of the '{@link co.watly.vapor.CommandCommon#getMillisecs <em>Millisecs</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Millisecs</em>' attribute.
   * @see #getMillisecs()
   * @generated
   */
  void setMillisecs(int value);

} // CommandCommon
