/**
 * This work is licensed under the 
 * Creative Commons Attribution-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit 
 * http://creativecommons.org/licenses/by-sa/4.0/ 
 * or send a letter to 
 * Creative Commons, 
 * PO Box 1866, Mountain View, 
 * CA 94042, USA.
 */
/**
 * generated by Xtext 2.13.0
 */
package co.watly.vapor;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see co.watly.vapor.VaporFactory
 * @model kind="package"
 * @generated
 */
public interface VaporPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "vapor";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.watly.co/Vapor";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "vapor";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  VaporPackage eINSTANCE = co.watly.vapor.impl.VaporPackageImpl.init();

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.ScheduledFlightImpl <em>Scheduled Flight</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.ScheduledFlightImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getScheduledFlight()
   * @generated
   */
  int SCHEDULED_FLIGHT = 0;

  /**
   * The feature id for the '<em><b>Date</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__DATE = 0;

  /**
   * The feature id for the '<em><b>Model</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__MODEL = 1;

  /**
   * The feature id for the '<em><b>Cost</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__COST = 2;

  /**
   * The feature id for the '<em><b>Commands</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT__COMMANDS = 3;

  /**
   * The number of structural features of the '<em>Scheduled Flight</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SCHEDULED_FLIGHT_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandImpl <em>Command</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommand()
   * @generated
   */
  int COMMAND = 1;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND__SPEED = 0;

  /**
   * The number of structural features of the '<em>Command</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandCommonImpl <em>Command Common</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandCommonImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommandCommon()
   * @generated
   */
  int COMMAND_COMMON = 2;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_COMMON__SPEED = COMMAND__SPEED;

  /**
   * The feature id for the '<em><b>Millisecs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_COMMON__MILLISECS = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Command Common</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_COMMON_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandUpImpl <em>Command Up</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandUpImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommandUp()
   * @generated
   */
  int COMMAND_UP = 3;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_UP__SPEED = COMMAND_COMMON__SPEED;

  /**
   * The feature id for the '<em><b>Millisecs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_UP__MILLISECS = COMMAND_COMMON__MILLISECS;

  /**
   * The number of structural features of the '<em>Command Up</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_UP_FEATURE_COUNT = COMMAND_COMMON_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandDownImpl <em>Command Down</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandDownImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommandDown()
   * @generated
   */
  int COMMAND_DOWN = 4;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_DOWN__SPEED = COMMAND_COMMON__SPEED;

  /**
   * The feature id for the '<em><b>Millisecs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_DOWN__MILLISECS = COMMAND_COMMON__MILLISECS;

  /**
   * The number of structural features of the '<em>Command Down</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_DOWN_FEATURE_COUNT = COMMAND_COMMON_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandLeftImpl <em>Command Left</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandLeftImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommandLeft()
   * @generated
   */
  int COMMAND_LEFT = 5;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_LEFT__SPEED = COMMAND_COMMON__SPEED;

  /**
   * The feature id for the '<em><b>Millisecs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_LEFT__MILLISECS = COMMAND_COMMON__MILLISECS;

  /**
   * The number of structural features of the '<em>Command Left</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_LEFT_FEATURE_COUNT = COMMAND_COMMON_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandRightImpl <em>Command Right</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandRightImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommandRight()
   * @generated
   */
  int COMMAND_RIGHT = 6;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_RIGHT__SPEED = COMMAND_COMMON__SPEED;

  /**
   * The feature id for the '<em><b>Millisecs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_RIGHT__MILLISECS = COMMAND_COMMON__MILLISECS;

  /**
   * The number of structural features of the '<em>Command Right</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_RIGHT_FEATURE_COUNT = COMMAND_COMMON_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandForwardImpl <em>Command Forward</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandForwardImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommandForward()
   * @generated
   */
  int COMMAND_FORWARD = 7;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FORWARD__SPEED = COMMAND_COMMON__SPEED;

  /**
   * The feature id for the '<em><b>Millisecs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FORWARD__MILLISECS = COMMAND_COMMON__MILLISECS;

  /**
   * The number of structural features of the '<em>Command Forward</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_FORWARD_FEATURE_COUNT = COMMAND_COMMON_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandBackImpl <em>Command Back</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandBackImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommandBack()
   * @generated
   */
  int COMMAND_BACK = 8;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_BACK__SPEED = COMMAND_COMMON__SPEED;

  /**
   * The feature id for the '<em><b>Millisecs</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_BACK__MILLISECS = COMMAND_COMMON__MILLISECS;

  /**
   * The number of structural features of the '<em>Command Back</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_BACK_FEATURE_COUNT = COMMAND_COMMON_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link co.watly.vapor.impl.CommandRotateImpl <em>Command Rotate</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see co.watly.vapor.impl.CommandRotateImpl
   * @see co.watly.vapor.impl.VaporPackageImpl#getCommandRotate()
   * @generated
   */
  int COMMAND_ROTATE = 9;

  /**
   * The feature id for the '<em><b>Speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_ROTATE__SPEED = COMMAND__SPEED;

  /**
   * The feature id for the '<em><b>Degrees</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_ROTATE__DEGREES = COMMAND_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Command Rotate</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMMAND_ROTATE_FEATURE_COUNT = COMMAND_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link co.watly.vapor.ScheduledFlight <em>Scheduled Flight</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Scheduled Flight</em>'.
   * @see co.watly.vapor.ScheduledFlight
   * @generated
   */
  EClass getScheduledFlight();

  /**
   * Returns the meta object for the attribute '{@link co.watly.vapor.ScheduledFlight#getDate <em>Date</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Date</em>'.
   * @see co.watly.vapor.ScheduledFlight#getDate()
   * @see #getScheduledFlight()
   * @generated
   */
  EAttribute getScheduledFlight_Date();

  /**
   * Returns the meta object for the attribute '{@link co.watly.vapor.ScheduledFlight#getModel <em>Model</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Model</em>'.
   * @see co.watly.vapor.ScheduledFlight#getModel()
   * @see #getScheduledFlight()
   * @generated
   */
  EAttribute getScheduledFlight_Model();

  /**
   * Returns the meta object for the attribute '{@link co.watly.vapor.ScheduledFlight#getCost <em>Cost</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Cost</em>'.
   * @see co.watly.vapor.ScheduledFlight#getCost()
   * @see #getScheduledFlight()
   * @generated
   */
  EAttribute getScheduledFlight_Cost();

  /**
   * Returns the meta object for the containment reference list '{@link co.watly.vapor.ScheduledFlight#getCommands <em>Commands</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Commands</em>'.
   * @see co.watly.vapor.ScheduledFlight#getCommands()
   * @see #getScheduledFlight()
   * @generated
   */
  EReference getScheduledFlight_Commands();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.Command <em>Command</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command</em>'.
   * @see co.watly.vapor.Command
   * @generated
   */
  EClass getCommand();

  /**
   * Returns the meta object for the attribute '{@link co.watly.vapor.Command#getSpeed <em>Speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Speed</em>'.
   * @see co.watly.vapor.Command#getSpeed()
   * @see #getCommand()
   * @generated
   */
  EAttribute getCommand_Speed();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.CommandCommon <em>Command Common</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Common</em>'.
   * @see co.watly.vapor.CommandCommon
   * @generated
   */
  EClass getCommandCommon();

  /**
   * Returns the meta object for the attribute '{@link co.watly.vapor.CommandCommon#getMillisecs <em>Millisecs</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Millisecs</em>'.
   * @see co.watly.vapor.CommandCommon#getMillisecs()
   * @see #getCommandCommon()
   * @generated
   */
  EAttribute getCommandCommon_Millisecs();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.CommandUp <em>Command Up</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Up</em>'.
   * @see co.watly.vapor.CommandUp
   * @generated
   */
  EClass getCommandUp();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.CommandDown <em>Command Down</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Down</em>'.
   * @see co.watly.vapor.CommandDown
   * @generated
   */
  EClass getCommandDown();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.CommandLeft <em>Command Left</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Left</em>'.
   * @see co.watly.vapor.CommandLeft
   * @generated
   */
  EClass getCommandLeft();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.CommandRight <em>Command Right</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Right</em>'.
   * @see co.watly.vapor.CommandRight
   * @generated
   */
  EClass getCommandRight();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.CommandForward <em>Command Forward</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Forward</em>'.
   * @see co.watly.vapor.CommandForward
   * @generated
   */
  EClass getCommandForward();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.CommandBack <em>Command Back</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Back</em>'.
   * @see co.watly.vapor.CommandBack
   * @generated
   */
  EClass getCommandBack();

  /**
   * Returns the meta object for class '{@link co.watly.vapor.CommandRotate <em>Command Rotate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Command Rotate</em>'.
   * @see co.watly.vapor.CommandRotate
   * @generated
   */
  EClass getCommandRotate();

  /**
   * Returns the meta object for the attribute '{@link co.watly.vapor.CommandRotate#getDegrees <em>Degrees</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Degrees</em>'.
   * @see co.watly.vapor.CommandRotate#getDegrees()
   * @see #getCommandRotate()
   * @generated
   */
  EAttribute getCommandRotate_Degrees();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  VaporFactory getVaporFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.ScheduledFlightImpl <em>Scheduled Flight</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.ScheduledFlightImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getScheduledFlight()
     * @generated
     */
    EClass SCHEDULED_FLIGHT = eINSTANCE.getScheduledFlight();

    /**
     * The meta object literal for the '<em><b>Date</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEDULED_FLIGHT__DATE = eINSTANCE.getScheduledFlight_Date();

    /**
     * The meta object literal for the '<em><b>Model</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEDULED_FLIGHT__MODEL = eINSTANCE.getScheduledFlight_Model();

    /**
     * The meta object literal for the '<em><b>Cost</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SCHEDULED_FLIGHT__COST = eINSTANCE.getScheduledFlight_Cost();

    /**
     * The meta object literal for the '<em><b>Commands</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SCHEDULED_FLIGHT__COMMANDS = eINSTANCE.getScheduledFlight_Commands();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandImpl <em>Command</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommand()
     * @generated
     */
    EClass COMMAND = eINSTANCE.getCommand();

    /**
     * The meta object literal for the '<em><b>Speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND__SPEED = eINSTANCE.getCommand_Speed();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandCommonImpl <em>Command Common</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandCommonImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommandCommon()
     * @generated
     */
    EClass COMMAND_COMMON = eINSTANCE.getCommandCommon();

    /**
     * The meta object literal for the '<em><b>Millisecs</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND_COMMON__MILLISECS = eINSTANCE.getCommandCommon_Millisecs();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandUpImpl <em>Command Up</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandUpImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommandUp()
     * @generated
     */
    EClass COMMAND_UP = eINSTANCE.getCommandUp();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandDownImpl <em>Command Down</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandDownImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommandDown()
     * @generated
     */
    EClass COMMAND_DOWN = eINSTANCE.getCommandDown();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandLeftImpl <em>Command Left</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandLeftImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommandLeft()
     * @generated
     */
    EClass COMMAND_LEFT = eINSTANCE.getCommandLeft();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandRightImpl <em>Command Right</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandRightImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommandRight()
     * @generated
     */
    EClass COMMAND_RIGHT = eINSTANCE.getCommandRight();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandForwardImpl <em>Command Forward</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandForwardImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommandForward()
     * @generated
     */
    EClass COMMAND_FORWARD = eINSTANCE.getCommandForward();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandBackImpl <em>Command Back</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandBackImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommandBack()
     * @generated
     */
    EClass COMMAND_BACK = eINSTANCE.getCommandBack();

    /**
     * The meta object literal for the '{@link co.watly.vapor.impl.CommandRotateImpl <em>Command Rotate</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see co.watly.vapor.impl.CommandRotateImpl
     * @see co.watly.vapor.impl.VaporPackageImpl#getCommandRotate()
     * @generated
     */
    EClass COMMAND_ROTATE = eINSTANCE.getCommandRotate();

    /**
     * The meta object literal for the '<em><b>Degrees</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COMMAND_ROTATE__DEGREES = eINSTANCE.getCommandRotate_Degrees();

  }

} //VaporPackage
