/**
 * This work is licensed under the 
 * Creative Commons Attribution-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit 
 * http://creativecommons.org/licenses/by-sa/4.0/ 
 * or send a letter to 
 * Creative Commons, 
 * PO Box 1866, Mountain View, 
 * CA 94042, USA.
 */
/**
 * generated by Xtext 2.13.0
 */
package co.watly.validation;

import co.watly.validation.AbstractVaporValidator;
import co.watly.vapor.ScheduledFlight;
import co.watly.vapor.VaporPackage;
import org.eclipse.xtext.validation.Check;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class VaporValidator extends AbstractVaporValidator {
  public final static String INVALID_DATE = "invalidDate";
  
  @Check
  public void checkGreetingStartsWithCapital(final ScheduledFlight scheduledFlight) {
    long _currentTimeMillis = System.currentTimeMillis();
    long _time = scheduledFlight.getDate().getTime();
    boolean _greaterEqualsThan = (_currentTimeMillis >= _time);
    if (_greaterEqualsThan) {
      this.error("Flight date must be greater than actual time", 
        VaporPackage.Literals.SCHEDULED_FLIGHT__DATE, 
        VaporValidator.INVALID_DATE);
    }
  }
}
