/**
 * This work is licensed under the 
 * Creative Commons Attribution-ShareAlike 4.0 International License. 
 * To view a copy of this license, visit 
 * http://creativecommons.org/licenses/by-sa/4.0/ 
 * or send a letter to 
 * Creative Commons, 
 * PO Box 1866, Mountain View, 
 * CA 94042, USA.
 */
/**
 * generated by Xtext 2.13.0
 */
package co.watly.ide;

import co.watly.VaporRuntimeModule;
import co.watly.VaporStandaloneSetup;
import co.watly.ide.VaporIdeModule;
import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class VaporIdeSetup extends VaporStandaloneSetup {
  @Override
  public Injector createInjector() {
    VaporRuntimeModule _vaporRuntimeModule = new VaporRuntimeModule();
    VaporIdeModule _vaporIdeModule = new VaporIdeModule();
    return Guice.createInjector(Modules2.mixin(_vaporRuntimeModule, _vaporIdeModule));
  }
}
